appname = casdoor
httpport = 8000
runmode = dev
driverName = postgres
dataSourceName = "user=casdoor_admin password=strong_password_123 host=casdoor-db port=5432 sslmode=disable dbname=casdoor_db"
dbName = casdoor_db
tableNamePrefix =
showSql = false
redisEndpoint =
defaultStorageProvider =
isCloudIntelligent = false
quota =
logPostData = false
logConfig = {"filename": "logs/casdoor.log", "level":6, "maxlines": 0, "maxsize":0, "daily":true, "maxdays":15, "color":true}
